site_name: subpatch
site_url: https://subpatch.net
docs_dir: website
theme:
  name: readthedocs
nav:
  - Home: 'index.md'
  - Explanations:
    - Introduction: 'exp/intro.md'
    - Pre-subpatch history: 'exp/history.md'
    - Requirements: 'exp/requirements.md'
    - Design decisions: 'exp/design.md'
    - Comparison to other tools: 'exp/comparison.md'
#   - Frequently Asked Questions : 'exp/faq.md'
  - Tutorials:
    - Installation: 'tut/installation.md'
    - Basic usage: 'tut/basic-usage.md'
  - How-to guides:
    - Project based on Yocto: 'howto/yocto.md'
  - Reference:
    - Command line arguments: 'ref/command-line.md'
    - Glossary: 'ref/glossary.md'
    - Releases: 'ref/releases.md'
  - Imprint: 'imprint.md'
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lengfeld/subpatch
copyright: Copyright Â© 2024 Stefan Lengfeld (This website is licensed under CC BY-SA 4.0)
